// ==================== LEVEL DEFINITIONS ====================

export const LEVELS = [
  { 
    id: 1, 
    name: "Beginner", 
    distance: 1000, 
    minSpeed: 5, 
    maxSpeed: 12, 
    spikeGapMin: 650, 
    spikeGapMax: 850, 
    wallGapMin: 1600, 
    wallGapMax: 2000, 
    targetScore: 8, 
    star1: 4, 
    star2: 6, 
    star3: 8, 
    hasWalls: false, 
    hasPowerups: false, 
    hasCollectibles: true, 
    collectibleRate: 0.5 
  },
  { 
    id: 2, 
    name: "Easy", 
    distance: 1000, 
    minSpeed: 5, 
    maxSpeed: 12, 
    spikeGapMin: 620, 
    spikeGapMax: 820, 
    wallGapMin: 1500, 
    wallGapMax: 1900, 
    targetScore: 12, 
    star1: 5, 
    star2: 9, 
    star3: 12, 
    hasWalls: false, 
    hasPowerups: false, 
    hasCollectibles: true, 
    collectibleRate: 0.5 
  },
  { 
    id: 3, 
    name: "Warming Up", 
    distance: 1000, 
    minSpeed: 5, 
    maxSpeed: 12, 
    spikeGapMin: 600, 
    spikeGapMax: 800, 
    wallGapMin: 1400, 
    wallGapMax: 1800, 
    targetScore: 14, 
    star1: 6, 
    star2: 11, 
    star3: 14, 
    hasWalls: true, 
    hasPowerups: true, 
    hasCollectibles: true, 
    collectibleRate: 0.55 
  },
  { 
    id: 4, 
    name: "Getting Tricky", 
    distance: 1000, 
    minSpeed: 5, 
    maxSpeed: 12, 
    spikeGapMin: 580, 
    spikeGapMax: 780, 
    wallGapMin: 1350, 
    wallGapMax: 1750, 
    targetScore: 16, 
    star1: 7, 
    star2: 13, 
    star3: 16, 
    hasWalls: true, 
    hasPowerups: true, 
    hasCollectibles: true, 
    collectibleRate: 0.55 
  },
  { 
    id: 5, 
    name: "Speedy", 
    distance: 1000, 
    minSpeed: 5, 
    maxSpeed: 12, 
    spikeGapMin: 560, 
    spikeGapMax: 760, 
    wallGapMin: 1300, 
    wallGapMax: 1700, 
    targetScore: 20, 
    star1: 9, 
    star2: 15, 
    star3: 20, 
    hasWalls: true, 
    hasPowerups: true, 
    hasCollectibles: true, 
    collectibleRate: 0.6 
  },
  { 
    id: 6, 
    name: "Intense", 
    distance: 1000, 
    minSpeed: 5, 
    maxSpeed: 12, 
    spikeGapMin: 540, 
    spikeGapMax: 740, 
    wallGapMin: 1250, 
    wallGapMax: 1650, 
    targetScore: 24, 
    star1: 11, 
    star2: 18, 
    star3: 24, 
    hasWalls: true, 
    hasPowerups: true, 
    hasCollectibles: true, 
    collectibleRate: 0.6 
  },
  { 
    id: 7, 
    name: "Challenging", 
    distance: 1000, 
    minSpeed: 5, 
    maxSpeed: 12, 
    spikeGapMin: 520, 
    spikeGapMax: 720, 
    wallGapMin: 1200, 
    wallGapMax: 1600, 
    targetScore: 28, 
    star1: 13, 
    star2: 22, 
    star3: 28, 
    hasWalls: true, 
    hasPowerups: true, 
    hasCollectibles: true, 
    collectibleRate: 0.65 
  },
  { 
    id: 8, 
    name: "Hard", 
    distance: 1000, 
    minSpeed: 5, 
    maxSpeed: 12, 
    spikeGapMin: 500, 
    spikeGapMax: 700, 
    wallGapMin: 1150, 
    wallGapMax: 1550, 
    targetScore: 32, 
    star1: 15, 
    star2: 25, 
    star3: 32, 
    hasWalls: true, 
    hasPowerups: true, 
    hasCollectibles: true, 
    collectibleRate: 0.65 
  },
  { 
    id: 9, 
    name: "Expert", 
    distance: 1000, 
    minSpeed: 5, 
    maxSpeed: 12, 
    spikeGapMin: 480, 
    spikeGapMax: 680, 
    wallGapMin: 1100, 
    wallGapMax: 1500, 
    targetScore: 36, 
    star1: 17, 
    star2: 28, 
    star3: 36, 
    hasWalls: true, 
    hasPowerups: true, 
    hasCollectibles: true, 
    collectibleRate: 0.7 
  },
  { 
    id: 10, 
    name: "Master", 
    distance: 1000, 
    minSpeed: 5, 
    maxSpeed: 12, 
    spikeGapMin: 460, 
    spikeGapMax: 660, 
    wallGapMin: 1050, 
    wallGapMax: 1450, 
    targetScore: 40, 
    star1: 19, 
    star2: 31, 
    star3: 40, 
    hasWalls: true, 
    hasPowerups: true, 
    hasCollectibles: true, 
    collectibleRate: 0.7 
  },
  { 
    id: 11, 
    name: "Insane", 
    distance: 1000, 
    minSpeed: 5, 
    maxSpeed: 12, 
    spikeGapMin: 440, 
    spikeGapMax: 640, 
    wallGapMin: 1000, 
    wallGapMax: 1400, 
    targetScore: 48, 
    star1: 22, 
    star2: 37, 
    star3: 48, 
    hasWalls: true, 
    hasPowerups: true, 
    hasCollectibles: true, 
    collectibleRate: 0.75 
  },
  { 
    id: 12, 
    name: "Impossible", 
    distance: 1000, 
    minSpeed: 5, 
    maxSpeed: 12, 
    spikeGapMin: 420, 
    spikeGapMax: 620, 
    wallGapMin: 950, 
    wallGapMax: 1350, 
    targetScore: 56, 
    star1: 25, 
    star2: 42, 
    star3: 56, 
    hasWalls: true, 
    hasPowerups: true, 
    hasCollectibles: true, 
    collectibleRate: 0.8 
  }
];

// Helper function to get level by ID
export function getLevelById(levelId) {
  return LEVELS.find(l => l.id === levelId) || LEVELS[0];
}
